
from sc2.ids.unit_typeid import UnitTypeId

UNIT_COUNTERS = {
    UnitTypeId.ROACH: {

        UnitTypeId.ZEALOT: +1,
        UnitTypeId.STALKER: +1,
        UnitTypeId.SENTRY: 0,
        UnitTypeId.ADEPT: +1,
        UnitTypeId.HIGHTEMPLAR: 0,
        UnitTypeId.DARKTEMPLAR: 0,
        UnitTypeId.ARCHON: 0,
        UnitTypeId.IMMORTAL: -1,
        UnitTypeId.COLOSSUS: .5,
        UnitTypeId.DISRUPTOR: 0,
        UnitTypeId.PHOENIX: -1,
        UnitTypeId.VOIDRAY: -1,
        UnitTypeId.ORACLE: -1,
        UnitTypeId.CARRIER: -1,
        UnitTypeId.TEMPEST: -1,

        UnitTypeId.MARINE: 0,
        UnitTypeId.MARAUDER: -1,
        UnitTypeId.REAPER: +1,
        UnitTypeId.GHOST: 0,
        UnitTypeId.HELLION: +1,
        UnitTypeId.SIEGETANK: 0,
        UnitTypeId.THOR: 0,
        UnitTypeId.WIDOWMINE: -1,
        UnitTypeId.CYCLONE: 0,
        UnitTypeId.VIKING: 0,
        UnitTypeId.RAVEN: 0,
        UnitTypeId.BANSHEE: -1,
        UnitTypeId.BATTLECRUISER: -1,
        UnitTypeId.LIBERATOR: -1,

        UnitTypeId.ZERGLING: +1,
        UnitTypeId.BANELING: +1,
        UnitTypeId.ROACH: 0,
        UnitTypeId.RAVAGER: 0,
        UnitTypeId.HYDRALISK: 0,
        UnitTypeId.MUTALISK: -1,
        UnitTypeId.CORRUPTOR: 0,
        UnitTypeId.BROODLORD: -1,
        UnitTypeId.ULTRALISK: -1,
        UnitTypeId.SWARMHOSTMP: -1,
        UnitTypeId.INFESTOR: 0,
        UnitTypeId.VIPER: 0,

    },
    UnitTypeId.HYDRALISK: {

        UnitTypeId.ZEALOT: 0,
        UnitTypeId.STALKER: +1,
        UnitTypeId.SENTRY: +1,
        UnitTypeId.ADEPT: 0,
        UnitTypeId.HIGHTEMPLAR: -1,
        UnitTypeId.DARKTEMPLAR: 0,
        UnitTypeId.ARCHON: 0,
        UnitTypeId.IMMORTAL: +1,
        UnitTypeId.COLOSSUS: -1,
        UnitTypeId.DISRUPTOR: -1,
        UnitTypeId.PHOENIX: 0,
        UnitTypeId.VOIDRAY: +1,
        UnitTypeId.ORACLE: +1,
        UnitTypeId.CARRIER: 0,
        UnitTypeId.TEMPEST: 0,

        UnitTypeId.MARINE: -1,
        UnitTypeId.MARAUDER: 0,
        UnitTypeId.REAPER: 0,
        UnitTypeId.GHOST: 0,
        UnitTypeId.HELLION: 0,
        UnitTypeId.SIEGETANK: -1,
        UnitTypeId.THOR: 0,
        UnitTypeId.WIDOWMINE: 0,
        UnitTypeId.CYCLONE: 0,
        UnitTypeId.VIKING: 0,
        UnitTypeId.RAVEN: 0,
        UnitTypeId.BANSHEE: +1,
        UnitTypeId.BATTLECRUISER: 0,
        UnitTypeId.LIBERATOR: 0,

        UnitTypeId.ZERGLING: -1,
        UnitTypeId.BANELING: -1,
        UnitTypeId.ROACH: +1,
        UnitTypeId.RAVAGER: 0,
        UnitTypeId.HYDRALISK: 0,
        UnitTypeId.MUTALISK: +1,
        UnitTypeId.CORRUPTOR: +1,
        UnitTypeId.BROODLORD: -1,
        UnitTypeId.ULTRALISK: 0,
        UnitTypeId.SWARMHOSTMP: -1,
        UnitTypeId.INFESTOR: 0,
        UnitTypeId.VIPER: +1,

    },
    UnitTypeId.ZERGLING: {

        UnitTypeId.ZEALOT: -1,
        UnitTypeId.STALKER: 0,
        UnitTypeId.SENTRY: -1,
        UnitTypeId.ADEPT: -1,
        UnitTypeId.HIGHTEMPLAR: +1,
        UnitTypeId.DARKTEMPLAR: 0,
        UnitTypeId.ARCHON: -1,
        UnitTypeId.IMMORTAL: +1,
        UnitTypeId.COLOSSUS: -1,
        UnitTypeId.DISRUPTOR: +1,
        UnitTypeId.PHOENIX: -1,
        UnitTypeId.VOIDRAY: -1,
        UnitTypeId.ORACLE: -1,
        UnitTypeId.CARRIER: -1,
        UnitTypeId.TEMPEST: -1,

        UnitTypeId.MARINE: 0,
        UnitTypeId.MARAUDER: +1,
        UnitTypeId.REAPER: 0,
        UnitTypeId.GHOST: 0,
        UnitTypeId.HELLION: -1,
        UnitTypeId.SIEGETANK: 0,
        UnitTypeId.THOR: +1,
        UnitTypeId.WIDOWMINE: 0,
        UnitTypeId.CYCLONE: +1,
        UnitTypeId.VIKING: 0,
        UnitTypeId.RAVEN: 0,
        UnitTypeId.BANSHEE: -1,
        UnitTypeId.BATTLECRUISER: -1,
        UnitTypeId.LIBERATOR: -1,

        UnitTypeId.ZERGLING: 0,
        UnitTypeId.BANELING: -1,
        UnitTypeId.ROACH: -1,
        UnitTypeId.RAVAGER: -1,
        UnitTypeId.HYDRALISK: +1,
        UnitTypeId.MUTALISK: -1,
        UnitTypeId.CORRUPTOR: 0,
        UnitTypeId.BROODLORD: -1,
        UnitTypeId.ULTRALISK: 0,
        UnitTypeId.SWARMHOSTMP: -1,
        UnitTypeId.INFESTOR: +1,
        UnitTypeId.VIPER: 0,

    },
    UnitTypeId.BANELING: {

        UnitTypeId.ZEALOT: 0,
        UnitTypeId.STALKER: -1,
        UnitTypeId.SENTRY: 0,
        UnitTypeId.ADEPT: -1,
        UnitTypeId.HIGHTEMPLAR: 0,
        UnitTypeId.DARKTEMPLAR: 0,
        UnitTypeId.ARCHON: -1,
        UnitTypeId.IMMORTAL: -1,
        UnitTypeId.COLOSSUS: -1,
        UnitTypeId.DISRUPTOR: -1,
        UnitTypeId.PHOENIX: -1,
        UnitTypeId.VOIDRAY: -1,
        UnitTypeId.ORACLE: -1,
        UnitTypeId.CARRIER: -1,
        UnitTypeId.TEMPEST: -1,

        UnitTypeId.MARINE: +1,
        UnitTypeId.MARAUDER: -1,
        UnitTypeId.REAPER: 0,
        UnitTypeId.GHOST: 0,
        UnitTypeId.HELLION: 0,
        UnitTypeId.SIEGETANK: 0,
        UnitTypeId.THOR: 0,
        UnitTypeId.WIDOWMINE: 0,
        UnitTypeId.CYCLONE: 0,
        UnitTypeId.VIKING: 0,
        UnitTypeId.RAVEN: 0,
        UnitTypeId.BANSHEE: -1,
        UnitTypeId.BATTLECRUISER: -1,
        UnitTypeId.LIBERATOR: -1,

        UnitTypeId.ZERGLING: +1,
        UnitTypeId.BANELING: +1,
        UnitTypeId.ROACH: -1,
        UnitTypeId.RAVAGER: -1,
        UnitTypeId.HYDRALISK: 0,
        UnitTypeId.MUTALISK: 0,
        UnitTypeId.CORRUPTOR: 0,
        UnitTypeId.BROODLORD: 0,
        UnitTypeId.ULTRALISK: 0,
        UnitTypeId.SWARMHOSTMP: -1,
        UnitTypeId.INFESTOR: +1,
        UnitTypeId.VIPER: 0,

    },
    # UnitTypeId.MUTALISK: {

    #     UnitTypeId.ZEALOT: +1,
    #     UnitTypeId.STALKER: -1,
    #     UnitTypeId.SENTRY: -1,
    #     UnitTypeId.ADEPT: +1,
    #     UnitTypeId.HIGHTEMPLAR: -1,
    #     UnitTypeId.DARKTEMPLAR: +1,
    #     UnitTypeId.ARCHON: -1,
    #     UnitTypeId.IMMORTAL: +1,
    #     UnitTypeId.COLOSSUS: +1,
    #     UnitTypeId.DISRUPTOR: +1,
    #     UnitTypeId.PHOENIX: -1,
    #     UnitTypeId.VOIDRAY: -1,
    #     UnitTypeId.ORACLE: +1,
    #     UnitTypeId.CARRIER: -1,
    #     UnitTypeId.TEMPEST: -1,

    #     UnitTypeId.MARINE: 0,
    #     UnitTypeId.MARAUDER: 0,
    #     UnitTypeId.REAPER: 0,
    #     UnitTypeId.GHOST: 0,
    #     UnitTypeId.HELLION: 0,
    #     UnitTypeId.SIEGETANK: 0,
    #     UnitTypeId.THOR: -1,
    #     UnitTypeId.WIDOWMINE: 0,
    #     UnitTypeId.CYCLONE: 0,
    #     UnitTypeId.VIKING: +1,
    #     UnitTypeId.RAVEN: +1,
    #     UnitTypeId.BANSHEE: +1,
    #     UnitTypeId.BATTLECRUISER: -1,
    #     UnitTypeId.LIBERATOR: -1,

    #     UnitTypeId.ZERGLING: 0,
    #     UnitTypeId.BANELING: 0,
    #     UnitTypeId.ROACH: 0,
    #     UnitTypeId.RAVAGER: 0,
    #     UnitTypeId.HYDRALISK: -1,
    #     UnitTypeId.MUTALISK: 0,
    #     UnitTypeId.CORRUPTOR: 0,
    #     UnitTypeId.BROODLORD: 0,
    #     UnitTypeId.ULTRALISK: +1,
    #     UnitTypeId.SWARMHOSTMP: +1,
    #     UnitTypeId.INFESTOR: +1,
    #     UnitTypeId.VIPER: 0,

    # },
    # UnitTypeId.CORRUPTOR: {

    #     UnitTypeId.ZEALOT: 0,
    #     UnitTypeId.STALKER: -1,
    #     UnitTypeId.SENTRY: 0,
    #     UnitTypeId.ADEPT: 0,
    #     UnitTypeId.HIGHTEMPLAR: 0,
    #     UnitTypeId.DARKTEMPLAR: 0,
    #     UnitTypeId.ARCHON: -1,
    #     UnitTypeId.IMMORTAL: 0,
    #     UnitTypeId.COLOSSUS: +1,
    #     UnitTypeId.DISRUPTOR: 0,
    #     UnitTypeId.PHOENIX: +1,
    #     UnitTypeId.VOIDRAY: -1,
    #     UnitTypeId.ORACLE: +1,
    #     UnitTypeId.CARRIER: +1,
    #     UnitTypeId.TEMPEST: +1,

    #     UnitTypeId.MARINE: 0,
    #     UnitTypeId.MARAUDER: 0,
    #     UnitTypeId.REAPER: 0,
    #     UnitTypeId.GHOST: 0,
    #     UnitTypeId.HELLION: 0,
    #     UnitTypeId.SIEGETANK: 0,
    #     UnitTypeId.THOR: 0,
    #     UnitTypeId.WIDOWMINE: 0,
    #     UnitTypeId.CYCLONE: 0,
    #     UnitTypeId.VIKING: -1,
    #     UnitTypeId.RAVEN: +1,
    #     UnitTypeId.BANSHEE: +1,
    #     UnitTypeId.BATTLECRUISER: +1,
    #     UnitTypeId.LIBERATOR: +1,

    #     UnitTypeId.ZERGLING: 0,
    #     UnitTypeId.BANELING: 0,
    #     UnitTypeId.ROACH: 0,
    #     UnitTypeId.RAVAGER: 0,
    #     UnitTypeId.HYDRALISK: -1,
    #     UnitTypeId.MUTALISK: +1,
    #     UnitTypeId.CORRUPTOR: 0,
    #     UnitTypeId.BROODLORD: +1,
    #     UnitTypeId.ULTRALISK: 0,
    #     UnitTypeId.SWARMHOSTMP: 0,
    #     UnitTypeId.INFESTOR: 0,
    #     UnitTypeId.VIPER: +1,

    # },
    UnitTypeId.BROODLORD: {

        UnitTypeId.ZEALOT: +1,
        UnitTypeId.STALKER: -1,
        UnitTypeId.SENTRY: +1,
        UnitTypeId.ADEPT: +1,
        UnitTypeId.HIGHTEMPLAR: +1,
        UnitTypeId.DARKTEMPLAR: +1,
        UnitTypeId.ARCHON: -1,
        UnitTypeId.IMMORTAL: +1,
        UnitTypeId.COLOSSUS: +1,
        UnitTypeId.DISRUPTOR: +1,
        UnitTypeId.PHOENIX: -1,
        UnitTypeId.VOIDRAY: -1,
        UnitTypeId.ORACLE: 0,
        UnitTypeId.CARRIER: -1,
        UnitTypeId.TEMPEST: -1,

        UnitTypeId.MARINE: +1,
        UnitTypeId.MARAUDER: +1,
        UnitTypeId.REAPER: +1,
        UnitTypeId.GHOST: 0,
        UnitTypeId.HELLION: 0,
        UnitTypeId.SIEGETANK: +1,
        UnitTypeId.THOR: 0,
        UnitTypeId.WIDOWMINE: +1,
        UnitTypeId.CYCLONE: 0,
        UnitTypeId.VIKING: -1,
        UnitTypeId.RAVEN: 0,
        UnitTypeId.BANSHEE: 0,
        UnitTypeId.BATTLECRUISER: -1,
        UnitTypeId.LIBERATOR: -1,

        UnitTypeId.ZERGLING: +1,
        UnitTypeId.BANELING: +1,
        UnitTypeId.ROACH: +1,
        UnitTypeId.RAVAGER: +1,
        UnitTypeId.HYDRALISK: +1,
        UnitTypeId.MUTALISK: -1,
        UnitTypeId.CORRUPTOR: -1,
        UnitTypeId.BROODLORD: 0,
        UnitTypeId.ULTRALISK: +1,
        UnitTypeId.SWARMHOSTMP: +1,
        UnitTypeId.INFESTOR: 0,
        UnitTypeId.VIPER: 0,

    },
    UnitTypeId.ULTRALISK: {

        UnitTypeId.ZEALOT: +1,
        UnitTypeId.STALKER: -1,
        UnitTypeId.SENTRY: +1,
        UnitTypeId.ADEPT: -1,
        UnitTypeId.HIGHTEMPLAR: +1,
        UnitTypeId.DARKTEMPLAR: +1,
        UnitTypeId.ARCHON: +1,
        UnitTypeId.IMMORTAL: -1,
        UnitTypeId.COLOSSUS: +1,
        UnitTypeId.DISRUPTOR: +1,
        UnitTypeId.PHOENIX: 0,
        UnitTypeId.VOIDRAY: -1,
        UnitTypeId.ORACLE: 0,
        UnitTypeId.CARRIER: -1,
        UnitTypeId.TEMPEST: -1,

        UnitTypeId.MARINE: +1,
        UnitTypeId.MARAUDER: +1,
        UnitTypeId.REAPER: +1,
        UnitTypeId.GHOST: 0,
        UnitTypeId.HELLION: +1,
        UnitTypeId.SIEGETANK: 0,
        UnitTypeId.THOR: 0,
        UnitTypeId.WIDOWMINE: +1,
        UnitTypeId.CYCLONE: 0,
        UnitTypeId.VIKING: 0,
        UnitTypeId.RAVEN: 0,
        UnitTypeId.BANSHEE: -1,
        UnitTypeId.BATTLECRUISER: -1,
        UnitTypeId.LIBERATOR: 0,

        UnitTypeId.ZERGLING: +1,
        UnitTypeId.BANELING: +1,
        UnitTypeId.ROACH: +1,
        UnitTypeId.RAVAGER: +1,
        UnitTypeId.HYDRALISK: 0,
        UnitTypeId.MUTALISK: -1,
        UnitTypeId.CORRUPTOR: 0,
        UnitTypeId.BROODLORD: -1,
        UnitTypeId.ULTRALISK: 0,
        UnitTypeId.SWARMHOSTMP: 0,
        UnitTypeId.INFESTOR: +1,
        UnitTypeId.VIPER: 0,

    },
}