
from sc2.ids.unit_typeid import UnitTypeId

UNIT_COUNTER_DICT = {
    
    UnitTypeId.ZEALOT: [UnitTypeId.HYDRALISK, UnitTypeId.ROACH, UnitTypeId.ZERGLING],
    UnitTypeId.STALKER: [UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING, UnitTypeId.ROACH],
    UnitTypeId.SENTRY: [UnitTypeId.HYDRALISK, UnitTypeId.ROACH, UnitTypeId.ZERGLING],
    UnitTypeId.ADEPT: [UnitTypeId.HYDRALISK, UnitTypeId.ROACH, UnitTypeId.ZERGLING],
    UnitTypeId.HIGHTEMPLAR: [UnitTypeId.ROACH, UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING],
    UnitTypeId.DARKTEMPLAR: [UnitTypeId.HYDRALISK, UnitTypeId.ROACH, UnitTypeId.ZERGLING],
    UnitTypeId.ARCHON: [UnitTypeId.ROACH, UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING],
    UnitTypeId.IMMORTAL: [UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING, UnitTypeId.ROACH],
    UnitTypeId.COLOSSUS: [UnitTypeId.ROACH, UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING],
    UnitTypeId.DISRUPTOR: [UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING, UnitTypeId.ROACH], 
    UnitTypeId.PHOENIX: [UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING, UnitTypeId.ROACH],
    UnitTypeId.VOIDRAY: [UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING, UnitTypeId.ROACH],
    UnitTypeId.ORACLE: [UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING, UnitTypeId.ROACH],
    UnitTypeId.CARRIER: [UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING, UnitTypeId.ROACH],
    UnitTypeId.TEMPEST: [UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING, UnitTypeId.ROACH],

    UnitTypeId.MARINE: [UnitTypeId.ROACH, UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING],
    UnitTypeId.MARAUDER: [UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING, UnitTypeId.ROACH],
    UnitTypeId.REAPER: [UnitTypeId.HYDRALISK, UnitTypeId.ROACH, UnitTypeId.ZERGLING],
    UnitTypeId.GHOST: [UnitTypeId.HYDRALISK, UnitTypeId.ROACH, UnitTypeId.ZERGLING],
    UnitTypeId.HELLION: [UnitTypeId.ROACH, UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING],
    UnitTypeId.SIEGETANK: [UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING, UnitTypeId.ROACH],
    UnitTypeId.THOR: [UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING, UnitTypeId.ROACH],
    UnitTypeId.WIDOWMINE: [UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING, UnitTypeId.ROACH],
    UnitTypeId.CYCLONE: [UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING, UnitTypeId.ROACH],
    UnitTypeId.VIKING: [UnitTypeId.HYDRALISK, UnitTypeId.ROACH, UnitTypeId.ZERGLING],
    UnitTypeId.RAVEN: [UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING, UnitTypeId.ROACH],
    UnitTypeId.BANSHEE: [UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING, UnitTypeId.ROACH],
    UnitTypeId.BATTLECRUISER: [UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING, UnitTypeId.ROACH],
    UnitTypeId.LIBERATOR: [UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING, UnitTypeId.ROACH],

    UnitTypeId.ZERGLING: [UnitTypeId.ROACH, UnitTypeId.ZERGLING, UnitTypeId.HYDRALISK],
    UnitTypeId.BANELING: [UnitTypeId.ROACH, UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING],
    UnitTypeId.ROACH: [UnitTypeId.ROACH, UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING],
    UnitTypeId.RAVAGER: [UnitTypeId.ROACH, UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING],
    UnitTypeId.HYDRALISK: [UnitTypeId.ROACH, UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING],
    UnitTypeId.MUTALISK: [UnitTypeId.HYDRALISK, UnitTypeId.ROACH, UnitTypeId.ZERGLING],
    UnitTypeId.CORRUPTOR: [UnitTypeId.HYDRALISK, UnitTypeId.ROACH, UnitTypeId.ZERGLING],
    UnitTypeId.BROODLORD: [UnitTypeId.HYDRALISK, UnitTypeId.ROACH, UnitTypeId.ZERGLING],
    UnitTypeId.ULTRALISK: [UnitTypeId.ROACH, UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING],
    UnitTypeId.SWARMHOSTMP: [UnitTypeId.HYDRALISK, UnitTypeId.ROACH, UnitTypeId.ZERGLING],
    UnitTypeId.INFESTOR: [UnitTypeId.HYDRALISK, UnitTypeId.ROACH, UnitTypeId.ZERGLING],
    UnitTypeId.VIPER: [UnitTypeId.HYDRALISK, UnitTypeId.ROACH, UnitTypeId.ZERGLING],

}

UNIT_COUNTER_MATRIX = {
    UnitTypeId.ROACH: {

        UnitTypeId.ZEALOT: +1,
        UnitTypeId.STALKER: +1,
        UnitTypeId.SENTRY: 0,
        UnitTypeId.ADEPT: +1,
        UnitTypeId.HIGHTEMPLAR: 0,
        UnitTypeId.DARKTEMPLAR: 0,
        UnitTypeId.ARCHON: 0,
        UnitTypeId.IMMORTAL: -1,
        UnitTypeId.COLOSSUS: 0,
        UnitTypeId.DISRUPTOR: 0,
        UnitTypeId.PHOENIX: -1,
        UnitTypeId.VOIDRAY: -1,
        UnitTypeId.ORACLE: -1,
        UnitTypeId.CARRIER: -1,
        UnitTypeId.TEMPEST: -1,

        UnitTypeId.MARINE: 0,
        UnitTypeId.MARAUDER: -1,
        UnitTypeId.REAPER: +1,
        UnitTypeId.GHOST: 0,
        UnitTypeId.HELLION: +1,
        UnitTypeId.SIEGETANK: 0,
        UnitTypeId.THOR: 0,
        UnitTypeId.WIDOWMINE: -1,
        UnitTypeId.CYCLONE: 0,
        UnitTypeId.VIKING: 0,
        UnitTypeId.RAVEN: 0,
        UnitTypeId.BANSHEE: -1,
        UnitTypeId.BATTLECRUISER: -1,
        UnitTypeId.LIBERATOR: -1,

        UnitTypeId.ZERGLING: +1,
        UnitTypeId.BANELING: +1,
        UnitTypeId.ROACH: 0,
        UnitTypeId.RAVAGER: 0,
        UnitTypeId.HYDRALISK: 0,
        UnitTypeId.MUTALISK: -1,
        UnitTypeId.CORRUPTOR: 0,
        UnitTypeId.BROODLORD: -1,
        UnitTypeId.ULTRALISK: -1,
        UnitTypeId.SWARMHOSTMP: 0,
        UnitTypeId.INFESTOR: 0,
        UnitTypeId.VIPER: 0,

    },
    UnitTypeId.HYDRALISK: {

        UnitTypeId.ZEALOT: 0,
        UnitTypeId.STALKER: +1,
        UnitTypeId.SENTRY: +1,
        UnitTypeId.ADEPT: 0,
        UnitTypeId.HIGHTEMPLAR: -1,
        UnitTypeId.DARKTEMPLAR: 0,
        UnitTypeId.ARCHON: 0,
        UnitTypeId.IMMORTAL: +1,
        UnitTypeId.COLOSSUS: -1,
        UnitTypeId.DISRUPTOR: -1,
        UnitTypeId.PHOENIX: 0,
        UnitTypeId.VOIDRAY: 0,
        UnitTypeId.ORACLE: 0,
        UnitTypeId.CARRIER: 0,
        UnitTypeId.TEMPEST: 0,

        UnitTypeId.MARINE: -1,
        UnitTypeId.MARAUDER: 0,
        UnitTypeId.REAPER: 0,
        UnitTypeId.GHOST: 0,
        UnitTypeId.HELLION: 0,
        UnitTypeId.SIEGETANK: -1,
        UnitTypeId.THOR: 0,
        UnitTypeId.WIDOWMINE: 0,
        UnitTypeId.CYCLONE: 0,
        UnitTypeId.VIKING: +1,
        UnitTypeId.RAVEN: +1,
        UnitTypeId.BANSHEE: +1,
        UnitTypeId.BATTLECRUISER: 0,
        UnitTypeId.LIBERATOR: +1,

        UnitTypeId.ZERGLING: -1,
        UnitTypeId.BANELING: -1,
        UnitTypeId.ROACH: 0,
        UnitTypeId.RAVAGER: 0,
        UnitTypeId.HYDRALISK: 0,
        UnitTypeId.MUTALISK: +1,
        UnitTypeId.CORRUPTOR: +1,
        UnitTypeId.BROODLORD: +1,
        UnitTypeId.ULTRALISK: 0,
        UnitTypeId.SWARMHOSTMP: -1,
        UnitTypeId.INFESTOR: 0,
        UnitTypeId.VIPER: +1,

    },
    UnitTypeId.CORRUPTOR: {

        UnitTypeId.ZEALOT: 0,
        UnitTypeId.STALKER: -1,
        UnitTypeId.SENTRY: -1,
        UnitTypeId.ADEPT: 0,
        UnitTypeId.HIGHTEMPLAR: 0,
        UnitTypeId.DARKTEMPLAR: 0,
        UnitTypeId.ARCHON: -1,
        UnitTypeId.IMMORTAL: 0,
        UnitTypeId.COLOSSUS: +1,
        UnitTypeId.DISRUPTOR: 0,
        UnitTypeId.PHOENIX: 0,
        UnitTypeId.VOIDRAY: 0,
        UnitTypeId.ORACLE: +1,
        UnitTypeId.CARRIER: 0,
        UnitTypeId.TEMPEST: 0,

        UnitTypeId.MARINE: -1,
        UnitTypeId.MARAUDER: 0,
        UnitTypeId.REAPER: 0,
        UnitTypeId.GHOST: -1,
        UnitTypeId.HELLION: 0,
        UnitTypeId.SIEGETANK: 0,
        UnitTypeId.THOR: 0,
        UnitTypeId.WIDOWMINE: 0,
        UnitTypeId.CYCLONE: 0,
        UnitTypeId.VIKING: 0,
        UnitTypeId.RAVEN: +1,
        UnitTypeId.BANSHEE: +1,
        UnitTypeId.BATTLECRUISER: 0,
        UnitTypeId.LIBERATOR: 0,

        UnitTypeId.ZERGLING: 0,
        UnitTypeId.BANELING: 0,
        UnitTypeId.ROACH: 0,
        UnitTypeId.RAVAGER: 0,
        UnitTypeId.HYDRALISK: -1,
        UnitTypeId.MUTALISK: 0,
        UnitTypeId.CORRUPTOR: 0,
        UnitTypeId.BROODLORD: +1,
        UnitTypeId.ULTRALISK: 0,
        UnitTypeId.SWARMHOSTMP: 0,
        UnitTypeId.INFESTOR: 0,
        UnitTypeId.VIPER: +1,

    },
    UnitTypeId.BROODLORD: {

        UnitTypeId.ZEALOT: +1,
        UnitTypeId.STALKER: -1,
        UnitTypeId.SENTRY: +1,
        UnitTypeId.ADEPT: +1,
        UnitTypeId.HIGHTEMPLAR: +1,
        UnitTypeId.DARKTEMPLAR: +1,
        UnitTypeId.ARCHON: 0,
        UnitTypeId.IMMORTAL: +1,
        UnitTypeId.COLOSSUS: +1,
        UnitTypeId.DISRUPTOR: +1,
        UnitTypeId.PHOENIX: -1,
        UnitTypeId.VOIDRAY: -1,
        UnitTypeId.ORACLE: 0,
        UnitTypeId.CARRIER: -1,
        UnitTypeId.TEMPEST: -1,

        UnitTypeId.MARINE: 0,
        UnitTypeId.MARAUDER: +1,
        UnitTypeId.REAPER: +1,
        UnitTypeId.GHOST: 0,
        UnitTypeId.HELLION: +1,
        UnitTypeId.SIEGETANK: +1,
        UnitTypeId.THOR: 0,
        UnitTypeId.WIDOWMINE: +1,
        UnitTypeId.CYCLONE: 0,
        UnitTypeId.VIKING: -1,
        UnitTypeId.RAVEN: 0,
        UnitTypeId.BANSHEE: 0,
        UnitTypeId.BATTLECRUISER: -1,
        UnitTypeId.LIBERATOR: -1,

        UnitTypeId.ZERGLING: +1,
        UnitTypeId.BANELING: +1,
        UnitTypeId.ROACH: +1,
        UnitTypeId.RAVAGER: +1,
        UnitTypeId.HYDRALISK: 0,
        UnitTypeId.MUTALISK: -1,
        UnitTypeId.CORRUPTOR: -1,
        UnitTypeId.BROODLORD: 0,
        UnitTypeId.ULTRALISK: +1,
        UnitTypeId.SWARMHOSTMP: +1,
        UnitTypeId.INFESTOR: +1,
        UnitTypeId.VIPER: -1,

    },
    UnitTypeId.ZERGLING: {

        UnitTypeId.ZEALOT: -1,
        UnitTypeId.STALKER: 0,
        UnitTypeId.SENTRY: -1,
        UnitTypeId.ADEPT: -1,
        UnitTypeId.HIGHTEMPLAR: +1,
        UnitTypeId.DARKTEMPLAR: 0,
        UnitTypeId.ARCHON: -1,
        UnitTypeId.IMMORTAL: +1,
        UnitTypeId.COLOSSUS: -1,
        UnitTypeId.DISRUPTOR: +1,
        UnitTypeId.PHOENIX: -1,
        UnitTypeId.VOIDRAY: -1,
        UnitTypeId.ORACLE: -1,
        UnitTypeId.CARRIER: -1,
        UnitTypeId.TEMPEST: -1,

        UnitTypeId.MARINE: 0,
        UnitTypeId.MARAUDER: +1,
        UnitTypeId.REAPER: 0,
        UnitTypeId.GHOST: 0,
        UnitTypeId.HELLION: -1,
        UnitTypeId.SIEGETANK: 0,
        UnitTypeId.THOR: +1,
        UnitTypeId.WIDOWMINE: 0,
        UnitTypeId.CYCLONE: +1,
        UnitTypeId.VIKING: 0,
        UnitTypeId.RAVEN: 0,
        UnitTypeId.BANSHEE: -1,
        UnitTypeId.BATTLECRUISER: -1,
        UnitTypeId.LIBERATOR: -1,

        UnitTypeId.ZERGLING: 0,
        UnitTypeId.BANELING: -1,
        UnitTypeId.ROACH: -1,
        UnitTypeId.RAVAGER: -1,
        UnitTypeId.HYDRALISK: +1,
        UnitTypeId.MUTALISK: -1,
        UnitTypeId.CORRUPTOR: 0,
        UnitTypeId.BROODLORD: -1,
        UnitTypeId.ULTRALISK: 0,
        UnitTypeId.SWARMHOSTMP: -1,
        UnitTypeId.INFESTOR: +1,
        UnitTypeId.VIPER: 0,

    },
    UnitTypeId.BANELING: {

        UnitTypeId.ZEALOT: 0,
        UnitTypeId.STALKER: -1,
        UnitTypeId.SENTRY: 0,
        UnitTypeId.ADEPT: -1,
        UnitTypeId.HIGHTEMPLAR: 0,
        UnitTypeId.DARKTEMPLAR: 0,
        UnitTypeId.ARCHON: -1,
        UnitTypeId.IMMORTAL: -1,
        UnitTypeId.COLOSSUS: -1,
        UnitTypeId.DISRUPTOR: -1,
        UnitTypeId.PHOENIX: -1,
        UnitTypeId.VOIDRAY: -1,
        UnitTypeId.ORACLE: -1,
        UnitTypeId.CARRIER: -1,
        UnitTypeId.TEMPEST: -1,

        UnitTypeId.MARINE: +1,
        UnitTypeId.MARAUDER: -1,
        UnitTypeId.REAPER: 0,
        UnitTypeId.GHOST: 0,
        UnitTypeId.HELLION: 0,
        UnitTypeId.SIEGETANK: 0,
        UnitTypeId.THOR: 0,
        UnitTypeId.WIDOWMINE: 0,
        UnitTypeId.CYCLONE: 0,
        UnitTypeId.VIKING: 0,
        UnitTypeId.RAVEN: 0,
        UnitTypeId.BANSHEE: -1,
        UnitTypeId.BATTLECRUISER: -1,
        UnitTypeId.LIBERATOR: -1,

        UnitTypeId.ZERGLING: +1,
        UnitTypeId.BANELING: +1,
        UnitTypeId.ROACH: -1,
        UnitTypeId.RAVAGER: -1,
        UnitTypeId.HYDRALISK: 0,
        UnitTypeId.MUTALISK: 0,
        UnitTypeId.CORRUPTOR: 0,
        UnitTypeId.BROODLORD: 0,
        UnitTypeId.ULTRALISK: 0,
        UnitTypeId.SWARMHOSTMP: -1,
        UnitTypeId.INFESTOR: +1,
        UnitTypeId.VIPER: 0,

    },
    UnitTypeId.MUTALISK: {

        UnitTypeId.ZEALOT: +1,
        UnitTypeId.STALKER: -1,
        UnitTypeId.SENTRY: -1,
        UnitTypeId.ADEPT: +1,
        UnitTypeId.HIGHTEMPLAR: -1,
        UnitTypeId.DARKTEMPLAR: +1,
        UnitTypeId.ARCHON: -1,
        UnitTypeId.IMMORTAL: +1,
        UnitTypeId.COLOSSUS: +1,
        UnitTypeId.DISRUPTOR: +1,
        UnitTypeId.PHOENIX: -1,
        UnitTypeId.VOIDRAY: -1,
        UnitTypeId.ORACLE: +1,
        UnitTypeId.CARRIER: -1,
        UnitTypeId.TEMPEST: -1,

        UnitTypeId.MARINE: 0,
        UnitTypeId.MARAUDER: 0,
        UnitTypeId.REAPER: 0,
        UnitTypeId.GHOST: 0,
        UnitTypeId.HELLION: 0,
        UnitTypeId.SIEGETANK: 0,
        UnitTypeId.THOR: -1,
        UnitTypeId.WIDOWMINE: 0,
        UnitTypeId.CYCLONE: 0,
        UnitTypeId.VIKING: +1,
        UnitTypeId.RAVEN: +1,
        UnitTypeId.BANSHEE: +1,
        UnitTypeId.BATTLECRUISER: -1,
        UnitTypeId.LIBERATOR: -1,

        UnitTypeId.ZERGLING: 0,
        UnitTypeId.BANELING: 0,
        UnitTypeId.ROACH: 0,
        UnitTypeId.RAVAGER: 0,
        UnitTypeId.HYDRALISK: -1,
        UnitTypeId.MUTALISK: 0,
        UnitTypeId.CORRUPTOR: 0,
        UnitTypeId.BROODLORD: 0,
        UnitTypeId.ULTRALISK: +1,
        UnitTypeId.SWARMHOSTMP: +1,
        UnitTypeId.INFESTOR: +1,
        UnitTypeId.VIPER: 0,

    },
    UnitTypeId.ULTRALISK: {

        UnitTypeId.ZEALOT: +1,
        UnitTypeId.STALKER: -1,
        UnitTypeId.SENTRY: +1,
        UnitTypeId.ADEPT: -1,
        UnitTypeId.HIGHTEMPLAR: +1,
        UnitTypeId.DARKTEMPLAR: +1,
        UnitTypeId.ARCHON: +1,
        UnitTypeId.IMMORTAL: -1,
        UnitTypeId.COLOSSUS: +1,
        UnitTypeId.DISRUPTOR: +1,
        UnitTypeId.PHOENIX: 0,
        UnitTypeId.VOIDRAY: -1,
        UnitTypeId.ORACLE: 0,
        UnitTypeId.CARRIER: -1,
        UnitTypeId.TEMPEST: -1,

        UnitTypeId.MARINE: +1,
        UnitTypeId.MARAUDER: +1,
        UnitTypeId.REAPER: +1,
        UnitTypeId.GHOST: 0,
        UnitTypeId.HELLION: +1,
        UnitTypeId.SIEGETANK: 0,
        UnitTypeId.THOR: 0,
        UnitTypeId.WIDOWMINE: +1,
        UnitTypeId.CYCLONE: 0,
        UnitTypeId.VIKING: 0,
        UnitTypeId.RAVEN: 0,
        UnitTypeId.BANSHEE: -1,
        UnitTypeId.BATTLECRUISER: -1,
        UnitTypeId.LIBERATOR: 0,

        UnitTypeId.ZERGLING: +1,
        UnitTypeId.BANELING: +1,
        UnitTypeId.ROACH: +1,
        UnitTypeId.RAVAGER: +1,
        UnitTypeId.HYDRALISK: 0,
        UnitTypeId.MUTALISK: -1,
        UnitTypeId.CORRUPTOR: 0,
        UnitTypeId.BROODLORD: -1,
        UnitTypeId.ULTRALISK: 0,
        UnitTypeId.SWARMHOSTMP: 0,
        UnitTypeId.INFESTOR: +1,
        UnitTypeId.VIPER: 0,

    },
}