from sc2.ids.unit_typeid import UnitTypeId

UNIT_COUNTER_DICT = {

    UnitTypeId.ZEALOT: [UnitTypeId.BROODLORD, UnitTypeId.ROACH, UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING],
    UnitTypeId.STALKER: [UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING, UnitTypeId.ROACH],
    UnitTypeId.SENTRY: [UnitTypeId.HYDRALISK, UnitTypeId.ROACH, UnitTypeId.ZERGLING],
    UnitTypeId.ADEPT: [UnitTypeId.BROODLORD, UnitTypeId.HYDRALISK, UnitTypeId.ROACH, UnitTypeId.ZERGLING],
    UnitTypeId.HIGHTEMPLAR: [UnitTypeId.ROACH, UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING],
    UnitTypeId.DARKTEMPLAR: [UnitTypeId.HYDRALISK, UnitTypeId.ROACH, UnitTypeId.ZERGLING],
    UnitTypeId.ARCHON: [UnitTypeId.ROACH, UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING],
    UnitTypeId.IMMORTAL: [UnitTypeId.BROODLORD, UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING, UnitTypeId.ROACH],
    UnitTypeId.COLOSSUS: [UnitTypeId.BROODLORD, UnitTypeId.CORRUPTOR, UnitTypeId.ROACH, UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING],
    UnitTypeId.DISRUPTOR: [UnitTypeId.BROODLORD, UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING, UnitTypeId.ROACH],
    UnitTypeId.PHOENIX: [UnitTypeId.CORRUPTOR, UnitTypeId.HYDRALISK, UnitTypeId.QUEEN],
    UnitTypeId.VOIDRAY: [UnitTypeId.HYDRALISK, UnitTypeId.QUEEN],
    UnitTypeId.ORACLE: [UnitTypeId.CORRUPTOR, UnitTypeId.HYDRALISK, UnitTypeId.QUEEN],
    UnitTypeId.TEMPEST: [UnitTypeId.CORRUPTOR, UnitTypeId.HYDRALISK, UnitTypeId.QUEEN],
    UnitTypeId.CARRIER: [UnitTypeId.CORRUPTOR, UnitTypeId.HYDRALISK, UnitTypeId.QUEEN],
    UnitTypeId.PHOTONCANNON: [UnitTypeId.RAVAGER, UnitTypeId.QUEEN, UnitTypeId.ZERGLING],
    # UnitTypeId.PROBE: [UnitTypeId.BROODLORD, UnitTypeId.HYDRALISK, UnitTypeId.ROACH, UnitTypeId.ZERGLING],

    UnitTypeId.MARINE: [UnitTypeId.BROODLORD, UnitTypeId.ROACH, UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING],
    UnitTypeId.MARAUDER: [UnitTypeId.BROODLORD, UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING, UnitTypeId.ROACH],
    UnitTypeId.REAPER: [UnitTypeId.HYDRALISK, UnitTypeId.ROACH, UnitTypeId.ZERGLING],
    UnitTypeId.GHOST: [UnitTypeId.BROODLORD, UnitTypeId.HYDRALISK, UnitTypeId.ROACH, UnitTypeId.ZERGLING],
    UnitTypeId.HELLION: [UnitTypeId.BROODLORD, UnitTypeId.ROACH, UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING],
    UnitTypeId.SIEGETANK: [UnitTypeId.BROODLORD, UnitTypeId.ZERGLING, UnitTypeId.HYDRALISK, UnitTypeId.ROACH],
    UnitTypeId.THOR: [UnitTypeId.BROODLORD, UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING, UnitTypeId.ROACH],
    UnitTypeId.WIDOWMINE: [UnitTypeId.BROODLORD, UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING, UnitTypeId.ROACH],
    UnitTypeId.CYCLONE: [UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING, UnitTypeId.ROACH],
    UnitTypeId.VIKINGFIGHTER: [UnitTypeId.HYDRALISK, UnitTypeId.ROACH, UnitTypeId.ZERGLING],
    UnitTypeId.VIKINGASSAULT: [UnitTypeId.HYDRALISK, UnitTypeId.ROACH, UnitTypeId.ZERGLING],
    UnitTypeId.RAVEN: [UnitTypeId.CORRUPTOR, UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING, UnitTypeId.ROACH],
    UnitTypeId.BANSHEE: [UnitTypeId.CORRUPTOR, UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING, UnitTypeId.ROACH],
    UnitTypeId.BATTLECRUISER: [UnitTypeId.CORRUPTOR, UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING, UnitTypeId.ROACH],
    UnitTypeId.LIBERATOR: [UnitTypeId.CORRUPTOR, UnitTypeId.HYDRALISK, UnitTypeId.QUEEN],
    # UnitTypeId.SCV: [UnitTypeId.BROODLORD, UnitTypeId.HYDRALISK, UnitTypeId.ROACH, UnitTypeId.ZERGLING],
    UnitTypeId.MEDIVAC: [UnitTypeId.CORRUPTOR, UnitTypeId.HYDRALISK, UnitTypeId.QUEEN],
    UnitTypeId.COMMANDCENTERFLYING: [UnitTypeId.CORRUPTOR],
    UnitTypeId.BARRACKSFLYING: [UnitTypeId.CORRUPTOR],
    UnitTypeId.FACTORYFLYING: [UnitTypeId.CORRUPTOR],
    UnitTypeId.STARPORTFLYING: [UnitTypeId.CORRUPTOR],
    UnitTypeId.BUNKER: [UnitTypeId.RAVAGER, UnitTypeId.QUEEN, UnitTypeId.ZERGLING],

    UnitTypeId.ZERGLING: [UnitTypeId.BROODLORD, UnitTypeId.ROACH, UnitTypeId.ZERGLING, UnitTypeId.HYDRALISK],
    UnitTypeId.ZERGLINGBURROWED: [UnitTypeId.BROODLORD, UnitTypeId.ROACH, UnitTypeId.ZERGLING, UnitTypeId.HYDRALISK],
    UnitTypeId.BANELING: [UnitTypeId.BROODLORD, UnitTypeId.ROACH, UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING],
    UnitTypeId.BANELINGBURROWED: [UnitTypeId.BROODLORD, UnitTypeId.ROACH, UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING],
    UnitTypeId.ROACH: [UnitTypeId.BROODLORD, UnitTypeId.ROACH, UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING],
    UnitTypeId.ROACHBURROWED: [UnitTypeId.BROODLORD, UnitTypeId.ROACH, UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING],
    UnitTypeId.RAVAGER: [UnitTypeId.BROODLORD, UnitTypeId.ROACH, UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING],
    UnitTypeId.RAVAGERBURROWED: [UnitTypeId.BROODLORD, UnitTypeId.ROACH, UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING],
    UnitTypeId.HYDRALISK: [UnitTypeId.BROODLORD, UnitTypeId.ROACH, UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING],
    UnitTypeId.HYDRALISKBURROWED: [UnitTypeId.BROODLORD, UnitTypeId.ROACH, UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING],
    UnitTypeId.MUTALISK: [UnitTypeId.CORRUPTOR, UnitTypeId.HYDRALISK, UnitTypeId.QUEEN],
    UnitTypeId.CORRUPTOR: [UnitTypeId.HYDRALISK, UnitTypeId.QUEEN],
    UnitTypeId.BROODLORD: [UnitTypeId.CORRUPTOR, UnitTypeId.HYDRALISK, UnitTypeId.ROACH, UnitTypeId.ZERGLING],
    UnitTypeId.ULTRALISK: [UnitTypeId.BROODLORD, UnitTypeId.ROACH, UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING],
    UnitTypeId.ULTRALISKBURROWED: [UnitTypeId.BROODLORD, UnitTypeId.ROACH, UnitTypeId.HYDRALISK, UnitTypeId.ZERGLING],
    UnitTypeId.SWARMHOSTMP: [UnitTypeId.HYDRALISK, UnitTypeId.ROACH, UnitTypeId.ZERGLING],
    UnitTypeId.SWARMHOSTBURROWEDMP: [UnitTypeId.HYDRALISK, UnitTypeId.ROACH, UnitTypeId.ZERGLING],
    UnitTypeId.INFESTOR: [UnitTypeId.HYDRALISK, UnitTypeId.ROACH, UnitTypeId.ZERGLING],
    UnitTypeId.INFESTORBURROWED: [UnitTypeId.HYDRALISK, UnitTypeId.ROACH, UnitTypeId.ZERGLING],
    UnitTypeId.VIPER: [UnitTypeId.HYDRALISK, UnitTypeId.ROACH, UnitTypeId.ZERGLING],
    # UnitTypeId.QUEEN: [UnitTypeId.BROODLORD, UnitTypeId.ROACH, UnitTypeId.ZERGLING, UnitTypeId.HYDRALISK],
    # UnitTypeId.QUEENBURROWED: [UnitTypeId.BROODLORD, UnitTypeId.ROACH, UnitTypeId.ZERGLING, UnitTypeId.HYDRALISK],
    UnitTypeId.SPINECRAWLER: [UnitTypeId.RAVAGER, UnitTypeId.QUEEN, UnitTypeId.ZERGLING],
    # UnitTypeId.DRONE: [UnitTypeId.BROODLORD, UnitTypeId.HYDRALISK, UnitTypeId.ROACH, UnitTypeId.ZERGLING],
    # UnitTypeId.DRONEBURROWED: [UnitTypeId.BROODLORD, UnitTypeId.HYDRALISK, UnitTypeId.ROACH, UnitTypeId.ZERGLING],

}